rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    org.hibernate: WARN
    at.technikum.paperless: DEBUG
spring:
  kafka:
    #read from env (docker-compose sets KAFKA_BOOTSTRAP_SERVERS=kafka:9092)
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # server is not consuming yet-but safe defaults
    consumer:
      group-id: rest-server-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "at.technikum.paperless.*"

paperless:
  kafka:
    topic: paperless.documents
    org.springframework.beans.factory: DEBUG
    org.springframework.context.annotation: DEBUG
